#!/bin/bash

DIR="$( cd "$( dirname "$0" )" && pwd )"

function symbolic_link {
  if [ -d $2 ]; then
    if [ -L $2 ]; then
      rm $2
    else
      rmdir $2
    fi
  else
    if [ -f $2 ]; then
      rm $2
    fi
  fi

  ln -s $1 $2
}

symbolic_link $DIR/vimrc ~/.vimrc
mkdir -p ~/.oh-my-zsh/custom/themes
symbolic_link $DIR/zsh/agnoster.zsh-theme ~/.oh-my-zsh/custom/themes/agnoster.zsh-theme
