#!/bin/bash

DIR="$( cd "$( dirname "$0" )" && pwd )"

function symbolic_link {
  if [ -d $2 ]; then
    if [ -L $2 ]; then
      rm $2
    else
      rmdir $2
    fi
  else
    if [ -f $2 ]; then
      rm $2
    fi
  fi

  ln -s $1 $2
}

symbolic_link $DIR/zsh/zshrc-pi ~/.zshrc
symbolic_link $DIR/zsh/themes/lukesmith.zsh-theme ~/.oh-my-zsh/themes/lukesmith.zsh-theme

#symbolic_link $DIR/vim/ ~/.vim
#symbolic_link $DIR/vim/vimrc ~/.vimrc
#symbolic_link $DIR/vim/gvimrc ~/.gvimrc
