#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

cd "$(dirname $0)"/..

sudo apt install gnupg2 tig htop -y

# find the installers and run them iteratively
find . -name install.sh | while read installer ; do sh -c "${installer}" ; done
